[package]
name = "LifeKeeper"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
tauri = "2.1.1"
ring = "0.17.8"
rand = "0.8"
regex = "1.7"    
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"   

